"""
NOTEBOOKS
"""
GET_NOTEBOOK = 'GET_NOTEBOOK'
UPDATE_NOTEBOOK = 'UPDATE_NOTEBOOK'
DELETE_NOTEBOOK = 'DELETE_NOTEBOOK'
MANAGE_NOTEBOOKS = 'MANAGE_NOTEBOOKS'
CREATE_NOTEBOOK = 'CREATE_NOTEBOOK'
NOTEBOOK_ALL = [
    GET_NOTEBOOK,
    DELETE_NOTEBOOK,
    UPDATE_NOTEBOOK,
]
