FROM public.ecr.aws/ubuntu/ubuntu:16.04_stable

ARG CONDA_DIR=/opt/conda
ENV PATH $CONDA_DIR/bin:$PATH
ARG SCRIPT_PATH

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        cmake \
        build-essential \
        curl \
        gcc \
        g++ \
        git && \
     
    # python environment
    curl -sL https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o conda.sh && \
    /bin/bash conda.sh -f -b -p $CONDA_DIR && \
    export PATH="$CONDA_DIR/bin:$PATH" && \
    conda config --set always_yes yes --set changeps1 no && \
    # lightgbm
    conda install -q -y numpy scipy scikit-learn pandas && \
    git clone --recursive --branch stable --depth 1 https://github.com/Microsoft/LightGBM && \
    cd LightGBM/python-package && python setup.py install && \
    # clean
    apt-get autoremove -y && apt-get clean && \
    conda clean -a -y && \
    rm -rf /usr/local/src/*

ENV PYTHONUNBUFFERED=TRUE
ENV PYTHONDONTWRITEBYTECODE=TRUE
ENV PATH="/opt/program:${PATH}"

COPY smjobs /opt/program

WORKDIR /opt/program

COPY smjobs/$SCRIPT_PATH train

RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install .


ENTRYPOINT ["python3"]