"""
Add module's permissions to the global permissions.
Contains permissions for sagemaker notebooks
"""

from dataall.db.permissions import (
    ENVIRONMENT_ALL,
    ENVIRONMENT_INVITED,
    RESOURCES_ALL_WITH_DESC,
    RESOURCES_ALL,
)

GET_NOTEBOOK = "GET_NOTEBOOK"
UPDATE_NOTEBOOK = "UPDATE_NOTEBOOK"
DELETE_NOTEBOOK = "DELETE_NOTEBOOK"

NOTEBOOK_ALL = [
    GET_NOTEBOOK,
    DELETE_NOTEBOOK,
    UPDATE_NOTEBOOK,
]

LIST_ENVIRONMENT_NOTEBOOKS = 'LIST_ENVIRONMENT_NOTEBOOKS'

ENVIRONMENT_ALL.append(LIST_ENVIRONMENT_NOTEBOOKS)
ENVIRONMENT_INVITED.append(LIST_ENVIRONMENT_NOTEBOOKS)

RESOURCES_ALL.append(NOTEBOOK_ALL)
RESOURCES_ALL.append(LIST_ENVIRONMENT_NOTEBOOKS)

RESOURCES_ALL_WITH_DESC[NOTEBOOK_ALL] = "Read/modify notebooks"
RESOURCES_ALL_WITH_DESC[LIST_ENVIRONMENT_NOTEBOOKS] = "List notebooks on this environment"


