"""
Add module's permissions to the global permissions.
Contains permissions for sagemaker notebooks
"""

from dataall.db.permissions import (
    ENVIRONMENT_ALL,
    ENVIRONMENT_INVITED,
    RESOURCES_ALL_WITH_DESC,
    RESOURCES_ALL,
    ENVIRONMENT_INVITATION_REQUEST,
)

GET_NOTEBOOK = "GET_NOTEBOOK"
UPDATE_NOTEBOOK = "UPDATE_NOTEBOOK"
DELETE_NOTEBOOK = "DELETE_NOTEBOOK"

NOTEBOOK_ALL = [
    GET_NOTEBOOK,
    DELETE_NOTEBOOK,
    UPDATE_NOTEBOOK,
]

LIST_ENVIRONMENT_NOTEBOOKS = 'LIST_ENVIRONMENT_NOTEBOOKS'

ENVIRONMENT_ALL.append(LIST_ENVIRONMENT_NOTEBOOKS)
ENVIRONMENT_INVITED.append(LIST_ENVIRONMENT_NOTEBOOKS)
ENVIRONMENT_INVITATION_REQUEST.append(LIST_ENVIRONMENT_NOTEBOOKS)

RESOURCES_ALL.extend(NOTEBOOK_ALL)
RESOURCES_ALL.append(LIST_ENVIRONMENT_NOTEBOOKS)

RESOURCES_ALL_WITH_DESC[LIST_ENVIRONMENT_NOTEBOOKS] = "List notebooks on this environment"
RESOURCES_ALL_WITH_DESC[GET_NOTEBOOK] = "General permission to list notebooks"
RESOURCES_ALL_WITH_DESC[DELETE_NOTEBOOK] = "Permission to delete notebooks"
RESOURCES_ALL_WITH_DESC[UPDATE_NOTEBOOK] = "Permission to edit notebooks"


