"""Add module's permissions to the global permissions"""
from dataall.db.permissions import (
    TENANT_ALL,
    TENANT_ALL_WITH_DESC,
    ENVIRONMENT_ALL,
    ENVIRONMENT_INVITATION_REQUEST,
    ENVIRONMENT_INVITED,
    RESOURCES_ALL_WITH_DESC,
    RESOURCES_ALL,
)

MANAGE_NOTEBOOKS = "MANAGE_NOTEBOOKS"
CREATE_NOTEBOOK = "CREATE_NOTEBOOK"
GET_NOTEBOOK = "GET_NOTEBOOK"
UPDATE_NOTEBOOK = "UPDATE_NOTEBOOK"
DELETE_NOTEBOOK = "DELETE_NOTEBOOK"

NOTEBOOK_ALL = [
    GET_NOTEBOOK,
    DELETE_NOTEBOOK,
    UPDATE_NOTEBOOK,
]

LIST_ENVIRONMENT_NOTEBOOKS = 'LIST_ENVIRONMENT_NOTEBOOKS'

ENVIRONMENT_ALL.append(CREATE_NOTEBOOK)
ENVIRONMENT_ALL.append(LIST_ENVIRONMENT_NOTEBOOKS)
ENVIRONMENT_INVITATION_REQUEST.append(CREATE_NOTEBOOK)
ENVIRONMENT_INVITED.append(CREATE_NOTEBOOK)
ENVIRONMENT_INVITED.append(LIST_ENVIRONMENT_NOTEBOOKS)

TENANT_ALL.append(MANAGE_NOTEBOOKS)
TENANT_ALL_WITH_DESC[MANAGE_NOTEBOOKS] = "Manage notebooks"

RESOURCES_ALL.append(CREATE_NOTEBOOK)
RESOURCES_ALL.append(LIST_ENVIRONMENT_NOTEBOOKS)
RESOURCES_ALL_WITH_DESC[CREATE_NOTEBOOK] = "Create notebooks on this environment"
RESOURCES_ALL_WITH_DESC[LIST_ENVIRONMENT_NOTEBOOKS] = "List notebooks on this environment"


