"""
Add module's permissions to the global permissions.
Contains permissions for Warehouses
There are different types of permissions:
TENANT_PERMISSIONS
    Granted to the Tenant group. For each resource we should define a corresponding MANAGE_<RESOURCE> permission
ENVIRONMENT_PERMISSIONS
    Granted to any group in an environment. For each resource we should define a list of actions regarding
    that resource that are executed on the environment (e.g. List resources X in an environment)
ENVIRONMENT_INVITED_PERMISSIONS

ENVIRONMENT_INVITATION_REQUEST

RESOURCE_PERMISSION
    Granted to any group. For each resource we should define a list of all actions that can be done on the resource.
    We also need to add the permissions for the Environment resource (ENVIRONMENT_PERMISSIONS)

"""

from dataall.core.permissions.permissions import (
    ENVIRONMENT_ALL,
    ENVIRONMENT_INVITED,
    RESOURCES_ALL_WITH_DESC,
    RESOURCES_ALL,
    ENVIRONMENT_INVITATION_REQUEST,
    TENANT_ALL,
    TENANT_ALL_WITH_DESC,
)

# Definition of TENANT_PERMISSIONS
MANAGE_WAREHOUSES = 'MANAGE_WAREHOUSES '

TENANT_ALL.append(MANAGE_WAREHOUSES)
TENANT_ALL_WITH_DESC[MANAGE_WAREHOUSES] = 'Manage Warehouse Connections and Consumers'


# Definition of ENVIRONMENT_PERMISSIONS
CREATE_WAREHOUSE_CONNECTION = 'CREATE_WAREHOUSE_CONNECTION'
CREATE_WAREHOUSE_CONSUMER = 'CREATE_WAREHOUSE_CONSUMER'


ENVIRONMENT_ALL.append(CREATE_WAREHOUSE_CONNECTION)
ENVIRONMENT_INVITED.append(CREATE_WAREHOUSE_CONNECTION)
ENVIRONMENT_INVITATION_REQUEST.append(CREATE_WAREHOUSE_CONNECTION)

ENVIRONMENT_ALL.append(CREATE_WAREHOUSE_CONSUMER)
ENVIRONMENT_INVITED.append(CREATE_WAREHOUSE_CONSUMER)
ENVIRONMENT_INVITATION_REQUEST.append(CREATE_WAREHOUSE_CONSUMER)

# Definition of RESOURCE_PERMISSIONS
UPDATE_WAREHOUSE_CONNECTION = 'UPDATE_WAREHOUSE_CONNECTION'
DELETE_WAREHOUSE_CONNECTION = 'DELETE_WAREHOUSE_CONNECTION'
UPDATE_WAREHOUSE_CONSUMER = 'UPDATE_WAREHOUSE_CONSUMER'
DELETE_WAREHOUSE_CONSUMER = 'DELETE_WAREHOUSE_CONSUMER'

WAREHOUSE_CONNECTION_ALL = [UPDATE_WAREHOUSE_CONNECTION, DELETE_WAREHOUSE_CONNECTION]

WAREHOUSE_CONSUMER_ALL = [UPDATE_WAREHOUSE_CONSUMER, DELETE_WAREHOUSE_CONSUMER]

RESOURCES_ALL.extend(WAREHOUSE_CONNECTION_ALL)
RESOURCES_ALL.extend(WAREHOUSE_CONSUMER_ALL)
RESOURCES_ALL.append(CREATE_WAREHOUSE_CONNECTION)
RESOURCES_ALL.append(CREATE_WAREHOUSE_CONSUMER)


RESOURCES_ALL_WITH_DESC[UPDATE_WAREHOUSE_CONNECTION] = 'Permission to update a Warehouse Connection'
RESOURCES_ALL_WITH_DESC[UPDATE_WAREHOUSE_CONSUMER] = 'Permission to update a Warehouse Consumer'
RESOURCES_ALL_WITH_DESC[DELETE_WAREHOUSE_CONNECTION] = 'Permission to delete a Warehouse Connection'
RESOURCES_ALL_WITH_DESC[DELETE_WAREHOUSE_CONSUMER] = 'Permission to delete a Warehouse Consumer'
RESOURCES_ALL_WITH_DESC[CREATE_WAREHOUSE_CONNECTION] = 'Create Warehouse Connections on this environment'
RESOURCES_ALL_WITH_DESC[CREATE_WAREHOUSE_CONSUMER] = 'Create Warehouse Consumer on this environment'
