from dataall.core.permissions.services.environment_permissions import (
    ENVIRONMENT_INVITED,
    ENVIRONMENT_INVITED_DEFAULT,
    ENVIRONMENT_ALL,
)

from dataall.core.permissions.services.resources_permissions import (
    RESOURCES_ALL,
    RESOURCES_ALL_WITH_DESC,
)

"""
CONNECTION PERMISSIONS FOR ENVIRONMENT
"""

LIST_ENVIRONMENT_CONNECTIONS = 'LIST_ENVIRONMENT_CONNECTIONS'

ENVIRONMENT_INVITED.append(LIST_ENVIRONMENT_CONNECTIONS)
ENVIRONMENT_INVITED_DEFAULT.append(LIST_ENVIRONMENT_CONNECTIONS)
ENVIRONMENT_ALL.append(LIST_ENVIRONMENT_CONNECTIONS)

RESOURCES_ALL.append(LIST_ENVIRONMENT_CONNECTIONS)
RESOURCES_ALL_WITH_DESC[LIST_ENVIRONMENT_CONNECTIONS] = 'LIST_ENVIRONMENT_CONNECTIONS'
