from dataall.core.permissions.permissions import (
    ENVIRONMENT_INVITED,
    ENVIRONMENT_INVITATION_REQUEST,
    ENVIRONMENT_ALL,
    TENANT_ALL,
    TENANT_ALL_WITH_DESC,
    RESOURCES_ALL,
    RESOURCES_ALL_WITH_DESC,
)


"""
DATAPIPELINE PERMISSIONS FOR ENVIRONMENT
"""
CREATE_PIPELINE = 'CREATE_PIPELINE'

ENVIRONMENT_INVITED.append(CREATE_PIPELINE)

ENVIRONMENT_INVITATION_REQUEST.append(CREATE_PIPELINE)

ENVIRONMENT_ALL.append(CREATE_PIPELINE)

RESOURCES_ALL.append(CREATE_PIPELINE)

RESOURCES_ALL_WITH_DESC[CREATE_PIPELINE] = CREATE_PIPELINE


"""
DATAPIPELINES
"""
MANAGE_PIPELINES = 'MANAGE_PIPELINES'

TENANT_ALL.append(MANAGE_PIPELINES)
TENANT_ALL_WITH_DESC[MANAGE_PIPELINES] = 'Manage pipelines'

GET_PIPELINE = 'GET_PIPELINE'
UPDATE_PIPELINE = 'UPDATE_PIPELINE'
DELETE_PIPELINE = 'DELETE_PIPELINE'
CREDENTIALS_PIPELINE = 'CREDENTIALS_PIPELINE'
PIPELINE_ALL = [
    CREATE_PIPELINE,
    GET_PIPELINE,
    UPDATE_PIPELINE,
    DELETE_PIPELINE,
    CREDENTIALS_PIPELINE,
]

RESOURCES_ALL.extend(PIPELINE_ALL)
for perm in PIPELINE_ALL:
    RESOURCES_ALL_WITH_DESC[perm] = perm
RESOURCES_ALL_WITH_DESC[CREATE_PIPELINE] = 'Create pipelines on this environment'
