from dataall.db.permissions import TENANT_ALL, TENANT_ALL_WITH_DESC, RESOURCES_ALL, RESOURCES_ALL_WITH_DESC

MANAGE_WORKSHEETS = 'MANAGE_WORKSHEETS'

TENANT_ALL.append(MANAGE_WORKSHEETS)
TENANT_ALL_WITH_DESC[MANAGE_WORKSHEETS] = 'Manage worksheets'

"""
WORKSHEETS
"""
GET_WORKSHEET = 'GET_WORKSHEET'
UPDATE_WORKSHEET = 'UPDATE_WORKSHEET'
DELETE_WORKSHEET = 'DELETE_WORKSHEET'
SHARE_WORKSHEET = 'SHARE_WORKSHEET'
RUN_WORKSHEET_QUERY = 'RUN_WORKSHEET_QUERY'
WORKSHEET_ALL = [
    GET_WORKSHEET,
    UPDATE_WORKSHEET,
    DELETE_WORKSHEET,
    SHARE_WORKSHEET,
    RUN_WORKSHEET_QUERY,
]
WORKSHEET_SHARED = [GET_WORKSHEET, UPDATE_WORKSHEET, RUN_WORKSHEET_QUERY]

RESOURCES_ALL.extend(WORKSHEET_ALL)

for perm in WORKSHEET_ALL:
    RESOURCES_ALL_WITH_DESC[perm] = perm