from dataall.core.permissions.services.resources_permissions import (
    RESOURCES_ALL,
    RESOURCES_ALL_WITH_DESC,
)
from dataall.core.permissions.services.tenant_permissions import TENANT_ALL, TENANT_ALL_WITH_DESC

MANAGE_GLOSSARIES = 'MANAGE_GLOSSARIES'

TENANT_ALL.append(MANAGE_GLOSSARIES)
TENANT_ALL_WITH_DESC[MANAGE_GLOSSARIES] = 'Manage glossaries'

"""
GLOSSARIES
"""
CREATE_CATEGORY = 'CREATE_CATEGORY'
CREATE_TERM = 'CREATE_TERM'
UPDATE_NODE = 'UPDATE_NODE'
DELETE_GLOSSARY = 'DELETE_GLOSSARY'
APPROVE_ASSOCIATION = 'APPROVE_ASSOCIATION'
GLOSSARY_ALL = [
    CREATE_CATEGORY,
    CREATE_TERM,
    UPDATE_NODE,
    DELETE_GLOSSARY,
    APPROVE_ASSOCIATION,
]

RESOURCES_ALL.extend(GLOSSARY_ALL)

for perm in GLOSSARY_ALL:
    RESOURCES_ALL_WITH_DESC[perm] = perm
