"""
ORGANIZATION PERMISSIONS
"""
CREATE_ORGANIZATION = 'CREATE_ORGANIZATION'
UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION'
DELETE_ORGANIZATION = 'DELETE_ORGANIZATION'
GET_ORGANIZATION = 'GET_ORGANIZATION'
LINK_ENVIRONMENT = 'LINK_ENVIRONMENT'
INVITE_ORGANIZATION_GROUP = 'INVITE_ORGANIZATION_GROUP'
REMOVE_ORGANIZATION_GROUP = 'REMOVE_ORGANIZATION_GROUP'
ORGANIZATION_ALL = [
    CREATE_ORGANIZATION,
    UPDATE_ORGANIZATION,
    DELETE_ORGANIZATION,
    LINK_ENVIRONMENT,
    GET_ORGANIZATION,
    INVITE_ORGANIZATION_GROUP,
    REMOVE_ORGANIZATION_GROUP,
]
ORGANIZATION_INVITED = [LINK_ENVIRONMENT, GET_ORGANIZATION]

"""
TENANT PERMISSIONS
"""
MANAGE_REDSHIFT_CLUSTERS = 'MANAGE_REDSHIFT_CLUSTERS'
MANAGE_DASHBOARDS = 'MANAGE_DASHBOARDS'
MANAGE_PIPELINES = 'MANAGE_PIPELINES'
MANAGE_GROUPS = 'MANAGE_GROUPS'
MANAGE_ENVIRONMENT = 'MANAGE_ENVIRONMENT'
MANAGE_GLOSSARIES = 'MANAGE_GLOSSARIES'
MANAGE_ENVIRONMENTS = 'MANAGE_ENVIRONMENTS'
MANAGE_ORGANIZATIONS = 'MANAGE_ORGANIZATIONS'
MANAGE_SGMSTUDIO_NOTEBOOKS = 'MANAGE_SGMSTUDIO_NOTEBOOKS'

"""
ENVIRONMENT
"""
UPDATE_ENVIRONMENT = 'UPDATE_ENVIRONMENT'
GET_ENVIRONMENT = 'GET_ENVIRONMENT'
DELETE_ENVIRONMENT = 'DELETE_ENVIRONMENT'
INVITE_ENVIRONMENT_GROUP = 'INVITE_ENVIRONMENT_GROUP'
REMOVE_ENVIRONMENT_GROUP = 'REMOVE_ENVIRONMENT_GROUP'
UPDATE_ENVIRONMENT_GROUP = 'UPDATE_ENVIRONMENT_GROUP'
ADD_ENVIRONMENT_CONSUMPTION_ROLES = 'ADD_ENVIRONMENT_CONSUMPTION_ROLES'
LIST_ENVIRONMENT_CONSUMPTION_ROLES = 'LIST_ENVIRONMENT_CONSUMPTION_ROLES'
LIST_ENVIRONMENT_GROUP_PERMISSIONS = 'LIST_ENVIRONMENT_GROUP_PERMISSIONS'
LIST_ENVIRONMENT_GROUPS = 'LIST_ENVIRONMENT_GROUPS'
CREDENTIALS_ENVIRONMENT = 'CREDENTIALS_ENVIRONMENT'
ENABLE_ENVIRONMENT_SUBSCRIPTIONS = 'ENABLE_ENVIRONMENT_SUBSCRIPTIONS'
DISABLE_ENVIRONMENT_SUBSCRIPTIONS = 'DISABLE_ENVIRONMENT_SUBSCRIPTIONS'
CREATE_SHARE_OBJECT = 'CREATE_SHARE_OBJECT'
LIST_ENVIRONMENT_SHARED_WITH_OBJECTS = 'LIST_ENVIRONMENT_SHARED_WITH_OBJECTS'
CREATE_REDSHIFT_CLUSTER = 'CREATE_REDSHIFT_CLUSTER'
LIST_ENVIRONMENT_REDSHIFT_CLUSTERS = 'LIST_ENVIRONMENT_REDSHIFT_CLUSTERS'
CREATE_DASHBOARD = 'CREATE_DASHBOARD'
LIST_ENVIRONMENT_DASHBOARDS = 'LIST_ENVIRONMENT_DASHBOARDS'
CREATE_PIPELINE = 'CREATE_PIPELINE'
LIST_PIPELINES = 'LIST_PIPELINES'
CREATE_NETWORK = 'CREATE_NETWORK'
LIST_ENVIRONMENT_NETWORKS = 'LIST_ENVIRONMENT_NETWORKS'


ENVIRONMENT_INVITED = [
    LIST_ENVIRONMENT_GROUP_PERMISSIONS,
    GET_ENVIRONMENT,
    LIST_ENVIRONMENT_GROUPS,
    LIST_ENVIRONMENT_CONSUMPTION_ROLES,
    CREATE_SHARE_OBJECT,
    LIST_ENVIRONMENT_SHARED_WITH_OBJECTS,
    CREATE_REDSHIFT_CLUSTER,
    LIST_ENVIRONMENT_REDSHIFT_CLUSTERS,
    CREATE_DASHBOARD,
    LIST_ENVIRONMENT_DASHBOARDS,
    INVITE_ENVIRONMENT_GROUP,
    ADD_ENVIRONMENT_CONSUMPTION_ROLES,
    CREATE_PIPELINE,
    LIST_PIPELINES,
    CREATE_NETWORK,
    LIST_ENVIRONMENT_NETWORKS,
]
ENVIRONMENT_INVITATION_REQUEST = [
    INVITE_ENVIRONMENT_GROUP,
    ADD_ENVIRONMENT_CONSUMPTION_ROLES,
    CREATE_SHARE_OBJECT,
    CREATE_REDSHIFT_CLUSTER,
    CREATE_DASHBOARD,
    CREATE_PIPELINE,
    CREATE_NETWORK,
]
ENVIRONMENT_ALL = [
    UPDATE_ENVIRONMENT,
    GET_ENVIRONMENT,
    DELETE_ENVIRONMENT,
    INVITE_ENVIRONMENT_GROUP,
    REMOVE_ENVIRONMENT_GROUP,
    UPDATE_ENVIRONMENT_GROUP,
    LIST_ENVIRONMENT_GROUP_PERMISSIONS,
    ADD_ENVIRONMENT_CONSUMPTION_ROLES,
    LIST_ENVIRONMENT_CONSUMPTION_ROLES,
    LIST_ENVIRONMENT_GROUPS,
    CREDENTIALS_ENVIRONMENT,
    ENABLE_ENVIRONMENT_SUBSCRIPTIONS,
    DISABLE_ENVIRONMENT_SUBSCRIPTIONS,
    CREATE_SHARE_OBJECT,
    CREATE_REDSHIFT_CLUSTER,
    LIST_ENVIRONMENT_REDSHIFT_CLUSTERS,
    LIST_ENVIRONMENT_SHARED_WITH_OBJECTS,
    CREATE_DASHBOARD,
    LIST_ENVIRONMENT_DASHBOARDS,
    CREATE_PIPELINE,
    LIST_PIPELINES,
    CREATE_NETWORK,
    LIST_ENVIRONMENT_NETWORKS,
]
"""
CONSUMPTION_ROLE
"""
REMOVE_ENVIRONMENT_CONSUMPTION_ROLE = 'REMOVE_ENVIRONMENT_CONSUMPTION_ROLE'
CONSUMPTION_ENVIRONMENT_ROLE_ALL = [
    LIST_ENVIRONMENT_CONSUMPTION_ROLES,
    ADD_ENVIRONMENT_CONSUMPTION_ROLES
]
CONSUMPTION_ROLE_ALL = [
    REMOVE_ENVIRONMENT_CONSUMPTION_ROLE
]

"""
SHARE OBJECT
"""
ADD_ITEM = 'ADD_ITEM'
REMOVE_ITEM = 'REMOVE_ITEM'
SUBMIT_SHARE_OBJECT = 'SUBMIT_SHARE_OBJECT'
APPROVE_SHARE_OBJECT = 'APPROVE_SHARE_OBJECT'
REJECT_SHARE_OBJECT = 'REJECT_SHARE_OBJECT'
DELETE_SHARE_OBJECT = 'DELETE_SHARE_OBJECT'
GET_SHARE_OBJECT = 'GET_SHARE_OBJECT'
LIST_SHARED_ITEMS = 'LIST_SHARED_ITEMS'
SHARE_OBJECT_REQUESTER = [
    ADD_ITEM,
    REMOVE_ITEM,
    SUBMIT_SHARE_OBJECT,
    GET_SHARE_OBJECT,
    LIST_SHARED_ITEMS,
    DELETE_SHARE_OBJECT,
]
SHARE_OBJECT_APPROVER = [
    ADD_ITEM,
    REMOVE_ITEM,
    SUBMIT_SHARE_OBJECT,
    APPROVE_SHARE_OBJECT,
    REJECT_SHARE_OBJECT,
    DELETE_SHARE_OBJECT,
    GET_SHARE_OBJECT,
    LIST_SHARED_ITEMS,
]
SHARE_OBJECT_ALL = [
    ADD_ITEM,
    REMOVE_ITEM,
    SUBMIT_SHARE_OBJECT,
    APPROVE_SHARE_OBJECT,
    REJECT_SHARE_OBJECT,
    DELETE_SHARE_OBJECT,
    GET_SHARE_OBJECT,
    LIST_SHARED_ITEMS,
]

"""
GLOSSARIES
"""
CREATE_CATEGORY = 'CREATE_CATEGORY'
CREATE_TERM = 'CREATE_TERM'
UPDATE_NODE = 'UPDATE_NODE'
DELETE_GLOSSARY = 'DELETE_GLOSSARY'
APPROVE_ASSOCIATION = 'APPROVE_ASSOCIATION'
GLOSSARY_ALL = [
    CREATE_CATEGORY,
    CREATE_TERM,
    UPDATE_NODE,
    DELETE_GLOSSARY,
    APPROVE_ASSOCIATION,
]
"""
TENANT ALL
"""

TENANT_ALL = [
    MANAGE_REDSHIFT_CLUSTERS,
    MANAGE_DASHBOARDS,
    MANAGE_PIPELINES,
    MANAGE_GLOSSARIES,
    MANAGE_GROUPS,
    MANAGE_ENVIRONMENTS,
    MANAGE_ORGANIZATIONS,
    MANAGE_SGMSTUDIO_NOTEBOOKS,
]

TENANT_ALL_WITH_DESC = {k: k for k in TENANT_ALL}
TENANT_ALL_WITH_DESC[MANAGE_DASHBOARDS] = 'Manage dashboards'
TENANT_ALL_WITH_DESC[MANAGE_REDSHIFT_CLUSTERS] = 'Manage Redshift clusters'
TENANT_ALL_WITH_DESC[MANAGE_GLOSSARIES] = 'Manage glossaries'
TENANT_ALL_WITH_DESC[MANAGE_ENVIRONMENTS] = 'Manage environments'
TENANT_ALL_WITH_DESC[MANAGE_GROUPS] = 'Manage teams'
TENANT_ALL_WITH_DESC[MANAGE_PIPELINES] = 'Manage pipelines'
TENANT_ALL_WITH_DESC[MANAGE_ORGANIZATIONS] = 'Manage organizations'
TENANT_ALL_WITH_DESC[MANAGE_SGMSTUDIO_NOTEBOOKS] = 'Manage ML studio notebooks'

"""
REDSHIFT CLUSTER
"""
GET_REDSHIFT_CLUSTER = 'GET_REDSHIFT_CLUSTER'
SHARE_REDSHIFT_CLUSTER = 'SHARE_REDSHIFT_CLUSTER'
DELETE_REDSHIFT_CLUSTER = 'DELETE_REDSHIFT_CLUSTER'
REBOOT_REDSHIFT_CLUSTER = 'REBOOT_REDSHIFT_CLUSTER'
RESUME_REDSHIFT_CLUSTER = 'RESUME_REDSHIFT_CLUSTER'
PAUSE_REDSHIFT_CLUSTER = 'PAUSE_REDSHIFT_CLUSTER'
ADD_DATASET_TO_REDSHIFT_CLUSTER = 'ADD_DATASET_TO_REDSHIFT_CLUSTER'
LIST_REDSHIFT_CLUSTER_DATASETS = 'LIST_REDSHIFT_CLUSTER_DATASETS'
REMOVE_DATASET_FROM_REDSHIFT_CLUSTER = 'REMOVE_DATASET_FROM_REDSHIFT_CLUSTER'
ENABLE_REDSHIFT_TABLE_COPY = 'ENABLE_REDSHIFT_TABLE_COPY'
DISABLE_REDSHIFT_TABLE_COPY = 'DISABLE_REDSHIFT_TABLE_COPY'
GET_REDSHIFT_CLUSTER_CREDENTIALS = 'GET_REDSHIFT_CLUSTER_CREDENTIALS'
REDSHIFT_CLUSTER_ALL = [
    GET_REDSHIFT_CLUSTER,
    SHARE_REDSHIFT_CLUSTER,
    DELETE_REDSHIFT_CLUSTER,
    REBOOT_REDSHIFT_CLUSTER,
    RESUME_REDSHIFT_CLUSTER,
    PAUSE_REDSHIFT_CLUSTER,
    ADD_DATASET_TO_REDSHIFT_CLUSTER,
    LIST_REDSHIFT_CLUSTER_DATASETS,
    REMOVE_DATASET_FROM_REDSHIFT_CLUSTER,
    ENABLE_REDSHIFT_TABLE_COPY,
    DISABLE_REDSHIFT_TABLE_COPY,
    GET_REDSHIFT_CLUSTER_CREDENTIALS,
]


"""
DASHBOARDS
"""
GET_DASHBOARD = 'GET_DASHBOARD'
UPDATE_DASHBOARD = 'UPDATE_DASHBOARD'
DELETE_DASHBOARD = 'DELETE_DASHBOARD'
DASHBOARD_URL = 'DASHBOARD_URL'
SHARE_DASHBOARD = 'SHARE_DASHBOARD'
DASHBOARD_ALL = [
    GET_DASHBOARD,
    UPDATE_DASHBOARD,
    DELETE_DASHBOARD,
    DASHBOARD_URL,
    SHARE_DASHBOARD,
]

"""
PIPELINES
"""
GET_PIPELINE = 'GET_PIPELINE'
UPDATE_PIPELINE = 'UPDATE_PIPELINE'
DELETE_PIPELINE = 'DELETE_PIPELINE'
CREDENTIALS_PIPELINE = 'CREDENTIALS_PIPELINE'
START_PIPELINE = 'START_PIPELINE'
PIPELINE_ALL = [
    CREATE_PIPELINE,
    GET_PIPELINE,
    UPDATE_PIPELINE,
    DELETE_PIPELINE,
    CREDENTIALS_PIPELINE,
    START_PIPELINE,
    LIST_PIPELINES,
]

"""
NETWORKS
"""
GET_NETWORK = 'GET_NETWORK'
UPDATE_NETWORK = 'UPDATE_NETWORK'
DELETE_NETWORK = 'DELETE_NETWORK'
NETWORK_ALL = [GET_NETWORK, UPDATE_NETWORK, DELETE_NETWORK]

"""
RESOURCES_ALL
"""
RESOURCES_ALL = (
    ORGANIZATION_ALL
    + ENVIRONMENT_ALL
    + CONSUMPTION_ROLE_ALL
    + SHARE_OBJECT_ALL
    + REDSHIFT_CLUSTER_ALL
    + GLOSSARY_ALL
    + DASHBOARD_ALL
    + PIPELINE_ALL
    + NETWORK_ALL
)

RESOURCES_ALL_WITH_DESC = {k: k for k in RESOURCES_ALL}
RESOURCES_ALL_WITH_DESC[CREATE_DASHBOARD] = 'Create dashboards on this environment'
RESOURCES_ALL_WITH_DESC[CREATE_REDSHIFT_CLUSTER] = 'Create Redshift clusters on this environment'
RESOURCES_ALL_WITH_DESC[INVITE_ENVIRONMENT_GROUP] = 'Invite other teams to this environment'
RESOURCES_ALL_WITH_DESC[ADD_ENVIRONMENT_CONSUMPTION_ROLES] = 'Add IAM consumption roles to this environment'
RESOURCES_ALL_WITH_DESC[CREATE_SHARE_OBJECT] = 'Request datasets access for this environment'
RESOURCES_ALL_WITH_DESC[CREATE_PIPELINE] = 'Create pipelines on this environment'
RESOURCES_ALL_WITH_DESC[CREATE_NETWORK] = 'Create networks on this environment'
