"""
Add module's permissions to the global permissions.
Contains permissions for Omics pipelines
"""

from dataall.db.permissions import (
    ENVIRONMENT_ALL,
    ENVIRONMENT_INVITED,
    RESOURCES_ALL_WITH_DESC,
    RESOURCES_ALL,
    ENVIRONMENT_INVITATION_REQUEST,
    TENANT_ALL,
    TENANT_ALL_WITH_DESC
)

GET_OMICS_PIPELINE = "GET_OMICS_PIPELINE"
UPDATE_OMICS_PIPELINE = "UPDATE_OMICS_PIPELINE"
DELETE_OMICS_PIPELINE = "DELETE_OMICS_PIPELINE"
CREATE_OMICS_PIPELINE = "CREATE_OMICS_PIPELINE"
MANAGE_OMICS_PIPELINES = "MANAGE_OMICS_PIPELINES"

OMICS_PIPELINE_ALL = [
    GET_OMICS_PIPELINE,
    DELETE_OMICS_PIPELINE,
    UPDATE_OMICS_PIPELINE,
]

LIST_ENVIRONMENT_OMICS_PIPELINES = 'LIST_ENVIRONMENT_OMICS_PIPELINES'

ENVIRONMENT_ALL.append(LIST_ENVIRONMENT_OMICS_PIPELINES)
ENVIRONMENT_ALL.append(CREATE_OMICS_PIPELINE)
ENVIRONMENT_INVITED.append(LIST_ENVIRONMENT_OMICS_PIPELINES)
ENVIRONMENT_INVITED.append(CREATE_OMICS_PIPELINE)
ENVIRONMENT_INVITATION_REQUEST.append(LIST_ENVIRONMENT_OMICS_PIPELINES)
ENVIRONMENT_INVITATION_REQUEST.append(CREATE_OMICS_PIPELINE)

TENANT_ALL.append(MANAGE_OMICS_PIPELINES)
TENANT_ALL_WITH_DESC[MANAGE_OMICS_PIPELINES] = "Manage Omics pipelines"


RESOURCES_ALL.append(CREATE_OMICS_PIPELINE)
RESOURCES_ALL.extend(OMICS_PIPELINE_ALL)
RESOURCES_ALL.append(LIST_ENVIRONMENT_OMICS_PIPELINES)

RESOURCES_ALL_WITH_DESC[CREATE_OMICS_PIPELINE] = "Create Omics pipelines on this environment"
RESOURCES_ALL_WITH_DESC[LIST_ENVIRONMENT_OMICS_PIPELINES] = "List Omics pipelines on this environment"
RESOURCES_ALL_WITH_DESC[GET_OMICS_PIPELINE] = "General permission to list Omics pipelines"
RESOURCES_ALL_WITH_DESC[DELETE_OMICS_PIPELINE] = "Permission to delete Omics pipelines"
RESOURCES_ALL_WITH_DESC[UPDATE_OMICS_PIPELINE] = "Permission to edit Omics pipelines"
