"""
Add module's permissions to the global permissions.
Contains permissions for Omics projects
"""

from dataall.db.permissions import (
    ENVIRONMENT_ALL,
    ENVIRONMENT_INVITED,
    RESOURCES_ALL_WITH_DESC,
    RESOURCES_ALL,
    ENVIRONMENT_INVITATION_REQUEST,
    TENANT_ALL,
    TENANT_ALL_WITH_DESC
)

GET_OMICS_PROJECT = "GET_OMICS_PROJECT"
UPDATE_OMICS_PROJECT = "UPDATE_OMICS_PROJECT"
DELETE_OMICS_PROJECT = "DELETE_OMICS_PROJECT"
CREATE_OMICS_PROJECT = "CREATE_OMICS_PROJECT"
MANAGE_OMICS_PROJECTS = "MANAGE_OMICS_PROJECTS"

OMICS_PROJECT_ALL = [
    GET_OMICS_PROJECT,
    DELETE_OMICS_PROJECT,
    UPDATE_OMICS_PROJECT,
]

LIST_ENVIRONMENT_OMICS_PROJECTS = 'LIST_ENVIRONMENT_OMICS_PROJECTS'

ENVIRONMENT_ALL.append(LIST_ENVIRONMENT_OMICS_PROJECTS)
ENVIRONMENT_ALL.append(CREATE_OMICS_PROJECT)
ENVIRONMENT_INVITED.append(LIST_ENVIRONMENT_OMICS_PROJECTS)
ENVIRONMENT_INVITED.append(CREATE_OMICS_PROJECT)
ENVIRONMENT_INVITATION_REQUEST.append(LIST_ENVIRONMENT_OMICS_PROJECTS)
ENVIRONMENT_INVITATION_REQUEST.append(CREATE_OMICS_PROJECT)

TENANT_ALL.append(MANAGE_OMICS_PROJECTS)
TENANT_ALL_WITH_DESC[MANAGE_OMICS_PROJECTS] = "Manage Omics projects"


RESOURCES_ALL.append(CREATE_OMICS_PROJECT)
RESOURCES_ALL.extend(OMICS_PROJECT_ALL)
RESOURCES_ALL.append(LIST_ENVIRONMENT_OMICS_PROJECTS)

RESOURCES_ALL_WITH_DESC[CREATE_OMICS_PROJECT] = "Create Omics projects on this environment"
RESOURCES_ALL_WITH_DESC[LIST_ENVIRONMENT_OMICS_PROJECTS] = "List Omics projects on this environment"
RESOURCES_ALL_WITH_DESC[GET_OMICS_PROJECT] = "General permission to list Omics projects"
RESOURCES_ALL_WITH_DESC[DELETE_OMICS_PROJECT] = "Permission to delete Omics projects"
RESOURCES_ALL_WITH_DESC[UPDATE_OMICS_PROJECT] = "Permission to edit Omics projects"
