"""
ENVIRONMENT
"""

UPDATE_ENVIRONMENT = 'UPDATE_ENVIRONMENT'
GET_ENVIRONMENT = 'GET_ENVIRONMENT'
DELETE_ENVIRONMENT = 'DELETE_ENVIRONMENT'
INVITE_ENVIRONMENT_GROUP = 'INVITE_ENVIRONMENT_GROUP'
REMOVE_ENVIRONMENT_GROUP = 'REMOVE_ENVIRONMENT_GROUP'
UPDATE_ENVIRONMENT_GROUP = 'UPDATE_ENVIRONMENT_GROUP'
ADD_ENVIRONMENT_CONSUMPTION_ROLES = 'ADD_ENVIRONMENT_CONSUMPTION_ROLES'
LIST_ENVIRONMENT_CONSUMPTION_ROLES = 'LIST_ENVIRONMENT_CONSUMPTION_ROLES'
LIST_ENVIRONMENT_GROUP_PERMISSIONS = 'LIST_ENVIRONMENT_GROUP_PERMISSIONS'
LIST_ENVIRONMENT_GROUPS = 'LIST_ENVIRONMENT_GROUPS'
CREDENTIALS_ENVIRONMENT = 'CREDENTIALS_ENVIRONMENT'
ENABLE_ENVIRONMENT_SUBSCRIPTIONS = 'ENABLE_ENVIRONMENT_SUBSCRIPTIONS'
DISABLE_ENVIRONMENT_SUBSCRIPTIONS = 'DISABLE_ENVIRONMENT_SUBSCRIPTIONS'
CREATE_NETWORK = 'CREATE_NETWORK'
LIST_ENVIRONMENT_NETWORKS = 'LIST_ENVIRONMENT_NETWORKS'


ENVIRONMENT_INVITATION_REQUEST = [
    INVITE_ENVIRONMENT_GROUP,
    ADD_ENVIRONMENT_CONSUMPTION_ROLES,
    CREATE_NETWORK,
]

ENVIRONMENT_INVITED_DEFAULT = [
    GET_ENVIRONMENT,
    LIST_ENVIRONMENT_GROUPS,
    LIST_ENVIRONMENT_CONSUMPTION_ROLES,
    LIST_ENVIRONMENT_GROUP_PERMISSIONS,
    LIST_ENVIRONMENT_NETWORKS,
    CREDENTIALS_ENVIRONMENT,
]

ENVIRONMENT_INVITED = ENVIRONMENT_INVITED_DEFAULT + ENVIRONMENT_INVITATION_REQUEST

ENVIRONMENT_ALL = [
    UPDATE_ENVIRONMENT,
    GET_ENVIRONMENT,
    DELETE_ENVIRONMENT,
    INVITE_ENVIRONMENT_GROUP,
    REMOVE_ENVIRONMENT_GROUP,
    UPDATE_ENVIRONMENT_GROUP,
    LIST_ENVIRONMENT_GROUP_PERMISSIONS,
    ADD_ENVIRONMENT_CONSUMPTION_ROLES,
    LIST_ENVIRONMENT_CONSUMPTION_ROLES,
    LIST_ENVIRONMENT_GROUPS,
    CREDENTIALS_ENVIRONMENT,
    ENABLE_ENVIRONMENT_SUBSCRIPTIONS,
    DISABLE_ENVIRONMENT_SUBSCRIPTIONS,
    CREATE_NETWORK,
    LIST_ENVIRONMENT_NETWORKS,
]
"""
CONSUMPTION_ROLE
"""
REMOVE_ENVIRONMENT_CONSUMPTION_ROLE = 'REMOVE_ENVIRONMENT_CONSUMPTION_ROLE'
CONSUMPTION_ENVIRONMENT_ROLE_ALL = [LIST_ENVIRONMENT_CONSUMPTION_ROLES, ADD_ENVIRONMENT_CONSUMPTION_ROLES]
CONSUMPTION_ROLE_ALL = [REMOVE_ENVIRONMENT_CONSUMPTION_ROLE]
