"""
ORGANIZATION PERMISSIONS
"""

CREATE_ORGANIZATION = 'CREATE_ORGANIZATION'
UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION'
DELETE_ORGANIZATION = 'DELETE_ORGANIZATION'
GET_ORGANIZATION = 'GET_ORGANIZATION'
LINK_ENVIRONMENT = 'LINK_ENVIRONMENT'
INVITE_ORGANIZATION_GROUP = 'INVITE_ORGANIZATION_GROUP'
REMOVE_ORGANIZATION_GROUP = 'REMOVE_ORGANIZATION_GROUP'
ORGANIZATION_ALL = [
    CREATE_ORGANIZATION,
    UPDATE_ORGANIZATION,
    DELETE_ORGANIZATION,
    LINK_ENVIRONMENT,
    GET_ORGANIZATION,
    INVITE_ORGANIZATION_GROUP,
    REMOVE_ORGANIZATION_GROUP,
]
ORGANIZATION_INVITED = [LINK_ENVIRONMENT, GET_ORGANIZATION]
