"""resource_thresholds_added

Revision ID: 2258cd8d6e9f
Revises: 5a798acc6282
Create Date: 2024-08-22 12:31:38.465650

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2258cd8d6e9f'
down_revision = 'ba2da94739ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'resource_threshold',
        sa.Column('actionUri', sa.String(length=64), nullable=False),
        sa.Column('username', sa.String(length=64), nullable=False),
        sa.Column('actionType', sa.String(length=64), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('count', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('actionUri'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_threshold')
    # ### end Alembic commands ###
