"""release 3.7.0

Revision ID: 2b40221043f1
Revises: 3ae3eeca475c
Create Date: 2021-12-02 11:12:57.959968

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b40221043f1'
down_revision = '3ae3eeca475c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('GlueCrawlerName', sa.String(), nullable=True))
    op.add_column('dataset', sa.Column('GlueCrawlerSchedule', sa.String(), nullable=True))
    op.add_column(
        'environment',
        sa.Column('EnvironmentDefaultAthenaWorkGroup', sa.String(), nullable=True),
    )
    op.add_column(
        'environment_group_permission',
        sa.Column('environmentAthenaWorkGroup', sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('environment_group_permission', 'environmentAthenaWorkGroup')
    op.drop_column('environment', 'EnvironmentDefaultAthenaWorkGroup')
    op.drop_column('dataset', 'GlueCrawlerSchedule')
    op.drop_column('dataset', 'GlueCrawlerName')
    # ### end Alembic commands ###
