"""redshift copy data location

Revision ID: 2ea02fe85af6
Revises: 4ab27e3b3d54
Create Date: 2021-07-15 07:17:38.392707

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ea02fe85af6'
down_revision = '4ab27e3b3d54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'redshiftcluster_datasettable',
        sa.Column('dataLocation', sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('redshiftcluster_datasettable', 'dataLocation')
    # ### end Alembic commands ###
