"""add_backfill_read_table_permissions

Revision ID: 59ab197fe648
Revises: c6d01930179d
Create Date: 2024-05-01 15:51:44.823037

"""

from alembic import op
from sqlalchemy import orm
from sqlalchemy import and_
from dataall.core.permissions.api.enums import PermissionType
from dataall.core.permissions.services.permission_service import PermissionService
from dataall.core.permissions.services.resource_policy_service import ResourcePolicyService
from dataall.modules.datasets_base.services.permissions import (
    DATASET_TABLE_READ,
    GET_DATASET_TABLE,
    PREVIEW_DATASET_TABLE,
)
from dataall.modules.datasets_base.db.dataset_models import DatasetTable, Dataset
from dataall.modules.dataset_sharing.db.share_object_models import ShareObject, ShareObjectItem
from dataall.modules.dataset_sharing.services.dataset_sharing_enums import ShareItemStatus, ShareableType

# revision identifiers, used by Alembic.
revision = '59ab197fe648'
down_revision = 'c6d01930179d'
branch_labels = None
depends_on = None


def get_session():
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    return session


def attach_dataset_table_read_permission(session, dataset: Dataset, table_uri):
    """
    Attach Folder permissions to dataset groups
    """
    permission_group = {
        dataset.SamlAdminGroupName,
        dataset.stewards if dataset.stewards is not None else dataset.SamlAdminGroupName,
    }
    for group in permission_group:
        ResourcePolicyService.attach_resource_policy(
            session=session,
            group=group,
            permissions=DATASET_TABLE_READ,
            resource_uri=table_uri,
            resource_type=DatasetTable.__name__,
        )


def upgrade():
    session = get_session()

    # Create new folder permission
    get_table_permission = PermissionService.save_permission(
        session=session,
        name=GET_DATASET_TABLE,
        description='GET_DATASET_TABLE',
        permission_type=PermissionType.RESOURCE.name,
    )

    preview_table_permission = PermissionService.save_permission(
        session=session,
        name=PREVIEW_DATASET_TABLE,
        description='PREVIEW_DATASET_TABLE',
        permission_type=PermissionType.RESOURCE.name,
    )

    # Grant table read permissions to all dataset owners and stewards
    print('Getting all Datasets and granting table permissions...')
    datasets: [Dataset] = session.query(Dataset).all()
    for dataset in datasets:
        tables: [DatasetTable] = session.query(DatasetTable).filter(DatasetTable.datasetUri == dataset.datasetUri).all()
        for table in tables:
            attach_dataset_table_read_permission(session, dataset, table.tableUri)

    # Grant table read permissions to share requesters with active shared folders
    print('Getting all Shares and granting table permissions...')
    shares: [ShareObject] = session.query(ShareObject).all()
    for share in shares:
        dataset: Dataset = session.query(Dataset).get(share.datasetUri)

        # Attach data.all read permissions to folders
        if dataset and share.groupUri != dataset.SamlAdminGroupName:
            share_table_items = (
                session.query(ShareObjectItem)
                .filter(
                    (
                        and_(
                            ShareObjectItem.shareUri == share.shareUri,
                            ShareObjectItem.itemType == ShareableType.Table.value,
                            ShareObjectItem.status.in_(
                                [
                                    ShareItemStatus.Share_Approved.value,
                                    ShareItemStatus.Share_Succeeded.value,
                                    ShareItemStatus.Share_In_Progress.value,
                                ]
                            ),
                        )
                    )
                )
                .all()
            )

            for item in share_table_items:
                ResourcePolicyService.attach_resource_policy(
                    session=session,
                    group=share.groupUri,
                    permissions=DATASET_TABLE_READ,
                    resource_uri=item.itemUri,
                    resource_type=DatasetTable.__name__,
                )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print('Skipping ... ')
    # ### end Alembic commands ###
