"""Add subnet ids columns

Revision ID: 5d5102986ce5
Revises: bd271a2780b2
Create Date: 2021-05-19 16:07:48.221086

"""

import os

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5d5102986ce5'
down_revision = 'bd271a2780b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    envname = os.getenv('envname', 'local')
    print('ENVNAME', envname)
    op.add_column(
        'vpc',
        sa.Column('privateSubnetIds', postgresql.ARRAY(sa.String()), nullable=True),
    )
    op.add_column(
        'vpc',
        sa.Column('publicSubnetIds', postgresql.ARRAY(sa.String()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vpc', 'publicSubnetIds')
    op.drop_column('vpc', 'privateSubnetIds')
    # ### end Alembic commands ###
