"""metadata_forms

Revision ID: 7c5b30fee306
Revises: 797dd1012be1
Create Date: 2024-07-19 15:03:20.671575

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c5b30fee306'
down_revision = '797dd1012be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'metadata_form',
        sa.Column('uri', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('SamlGroupName', sa.String(), nullable=False),
        sa.Column('visibility', sa.String(), nullable=False),
        sa.Column('homeEntity', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('uri', name='pk_metadata_form'),
    )
    op.create_table(
        'attached_metadata_form',
        sa.Column('metadataFormUri', sa.String(), nullable=False),
        sa.Column('uri', sa.String(), nullable=False),
        sa.Column('entityUri', sa.String(), nullable=False),
        sa.Column('entityType', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['metadataFormUri'], ['metadata_form.uri'], name='fk_attached_mf_uri'),
        sa.PrimaryKeyConstraint('uri', name='pk_attached_metadata_form'),
    )
    op.create_table(
        'metadata_form_enforcement_rule',
        sa.Column('uri', sa.String(), nullable=False),
        sa.Column('metadataFormUri', sa.String(), nullable=False),
        sa.Column('level', sa.String(), nullable=False),
        sa.Column('entityTypes', postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column('severity', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['metadataFormUri'], ['metadata_form.uri'], name='fk_mf_enforced_uri'),
        sa.PrimaryKeyConstraint('uri', name='pk_metadata_form_enforcement_rule'),
    )
    op.create_table(
        'metadata_form_field',
        sa.Column('metadataFormUri', sa.String(), nullable=True),
        sa.Column('uri', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('required', sa.Boolean(), nullable=False),
        sa.Column('glossaryNodeUri', sa.String(), nullable=True),
        sa.Column('possibleValues', postgresql.ARRAY(sa.String()), nullable=True),
        sa.ForeignKeyConstraint(['glossaryNodeUri'], ['glossary_node.nodeUri'], name='fk_mf_field_glossary_node'),
        sa.ForeignKeyConstraint(['metadataFormUri'], ['metadata_form.uri'], name='fk_mf_filed_form_uri'),
        sa.PrimaryKeyConstraint('uri', name='pk_metadata_form_field'),
    )
    op.create_table(
        'attached_metadata_form_field',
        sa.Column('attachedFormUri', sa.String(), nullable=False),
        sa.Column('fieldUri', sa.String(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['attachedFormUri'], ['attached_metadata_form.uri'], name='fk_attached_field_mf_uri'),
        sa.ForeignKeyConstraint(['fieldUri'], ['metadata_form_field.uri'], name='fk_attached_field_uri'),
        sa.PrimaryKeyConstraint('attachedFormUri', 'fieldUri', name='pk_attached_metadata_form_field'),
    )
    op.create_table(
        'boolean_attached_metadata_form_field',
        sa.Column('attachedFormUri', sa.String(), nullable=False),
        sa.Column('fieldUri', sa.String(), nullable=False),
        sa.Column('value', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['attachedFormUri', 'fieldUri'],
            ['attached_metadata_form_field.attachedFormUri', 'attached_metadata_form_field.fieldUri'],
            name='fk_b_field',
        ),
        sa.PrimaryKeyConstraint('attachedFormUri', 'fieldUri', name='pk_boolean_attached_metadata_form_field'),
    )
    op.create_table(
        'glossary_term_attached_metadata_form_field',
        sa.Column('attachedFormUri', sa.String(), nullable=False),
        sa.Column('fieldUri', sa.String(), nullable=False),
        sa.Column('value', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['attachedFormUri', 'fieldUri'],
            ['attached_metadata_form_field.attachedFormUri', 'attached_metadata_form_field.fieldUri'],
            name='fk_gt_field',
        ),
        sa.PrimaryKeyConstraint('attachedFormUri', 'fieldUri', name='pk_glossary_term_attached_metadata_form_field'),
    )
    op.create_table(
        'integer_attached_metadata_form_field',
        sa.Column('attachedFormUri', sa.String(), nullable=False),
        sa.Column('fieldUri', sa.String(), nullable=False),
        sa.Column('value', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['attachedFormUri', 'fieldUri'],
            ['attached_metadata_form_field.attachedFormUri', 'attached_metadata_form_field.fieldUri'],
            name='fk_i_field',
        ),
        sa.PrimaryKeyConstraint('attachedFormUri', 'fieldUri', name='pk_integer_attached_metadata_form_field'),
    )
    op.create_table(
        'string_attached_metadata_form_field',
        sa.Column('attachedFormUri', sa.String(), nullable=False),
        sa.Column('fieldUri', sa.String(), nullable=False),
        sa.Column('value', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['attachedFormUri', 'fieldUri'],
            ['attached_metadata_form_field.attachedFormUri', 'attached_metadata_form_field.fieldUri'],
            name='fk_s_field',
        ),
        sa.PrimaryKeyConstraint('attachedFormUri', 'fieldUri', name='pk_string_attached_metadata_form_field'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('string_attached_metadata_form_field')
    op.drop_table('integer_attached_metadata_form_field')
    op.drop_table('glossary_term_attached_metadata_form_field')
    op.drop_table('boolean_attached_metadata_form_field')
    op.drop_table('attached_metadata_form_field')
    op.drop_table('metadata_form_field')
    op.drop_table('metadata_form_enforcement_rule')
    op.drop_table('attached_metadata_form')
    op.drop_table('metadata_form')
    # ### end Alembic commands ###
