"""add_dataall_migration_version

Revision ID: acecf063195a
Revises: 797dd1012be1
Create Date: 2024-07-02 17:25:37.381236

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acecf063195a'
down_revision = '797dd1012be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'dataall_migrations',
        sa.Column('revision', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('revision', name='revision_pkey'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dataall_migrations')
    # ### end Alembic commands ###
