"""new permissions model

Revision ID: bc77fef9d0b2
Revises: 2ea02fe85af6
Create Date: 2021-08-03 07:51:18.202980

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc77fef9d0b2'
down_revision = '2ea02fe85af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'permission',
        sa.Column('permissionUri', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('type', sa.Enum('TENANT', 'RESOURCE', name='permissiontype'), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=True),
        sa.Column('updated', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('permissionUri'),
    )
    op.create_index(op.f('ix_permission_name'), 'permission', ['name'], unique=False)
    op.create_table(
        'resource_policy',
        sa.Column('sid', sa.String(), nullable=False),
        sa.Column('resourceUri', sa.String(), nullable=False),
        sa.Column('resourceType', sa.String(), nullable=False),
        sa.Column('principalId', sa.String(), nullable=False),
        sa.Column(
            'principalType',
            sa.Enum('USER', 'GROUP', 'SERVICE', name='rp_principal_type'),
            nullable=True,
        ),
        sa.Column('created', sa.DateTime(), nullable=True),
        sa.Column('updated', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('sid'),
    )
    op.create_index(
        op.f('ix_resource_policy_principalId'),
        'resource_policy',
        ['principalId'],
        unique=False,
    )
    op.create_index(
        op.f('ix_resource_policy_resourceType'),
        'resource_policy',
        ['resourceType'],
        unique=False,
    )
    op.create_index(
        op.f('ix_resource_policy_resourceUri'),
        'resource_policy',
        ['resourceUri'],
        unique=False,
    )
    op.create_table(
        'tenant',
        sa.Column('tenantUri', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('created', sa.DateTime(), nullable=True),
        sa.Column('updated', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('tenantUri'),
    )
    op.create_index(op.f('ix_tenant_name'), 'tenant', ['name'], unique=True)
    op.create_table(
        'resource_policy_permission',
        sa.Column('sid', sa.String(), nullable=False),
        sa.Column('permissionUri', sa.String(), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=True),
        sa.Column('updated', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['permissionUri'],
            ['permission.permissionUri'],
        ),
        sa.ForeignKeyConstraint(
            ['sid'],
            ['resource_policy.sid'],
        ),
        sa.PrimaryKeyConstraint('sid', 'permissionUri'),
    )
    op.create_table(
        'tenant_policy',
        sa.Column('sid', sa.String(), nullable=False),
        sa.Column('tenantUri', sa.String(), nullable=False),
        sa.Column('principalId', sa.String(), nullable=False),
        sa.Column(
            'principalType',
            sa.Enum('USER', 'GROUP', 'SERVICE', name='tenant_principal_type'),
            nullable=True,
        ),
        sa.Column('created', sa.DateTime(), nullable=True),
        sa.Column('updated', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['tenantUri'],
            ['tenant.tenantUri'],
        ),
        sa.PrimaryKeyConstraint('sid'),
    )
    op.create_index(
        op.f('ix_tenant_policy_principalId'),
        'tenant_policy',
        ['principalId'],
        unique=False,
    )
    op.create_table(
        'tenant_policy_permission',
        sa.Column('sid', sa.String(), nullable=False),
        sa.Column('permissionUri', sa.String(), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=True),
        sa.Column('updated', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['permissionUri'],
            ['permission.permissionUri'],
        ),
        sa.ForeignKeyConstraint(
            ['sid'],
            ['tenant_policy.sid'],
        ),
        sa.PrimaryKeyConstraint('sid', 'permissionUri'),
    )
    op.add_column('dashboardshare', sa.Column('owner', sa.String(), nullable=True))
    op.add_column('dataset', sa.Column('stewards', sa.String(), nullable=True))
    op.add_column(
        'environment_group_permission',
        sa.Column('invitedBy', sa.String(), nullable=True),
    )
    op.add_column(
        'environment_group_permission',
        sa.Column('environmentIAMRoleArn', sa.String(), nullable=True),
    )
    op.add_column(
        'environment_group_permission',
        sa.Column('environmentIAMRoleName', sa.String(), nullable=True),
    )
    op.add_column(
        'environment_group_permission',
        sa.Column('description', sa.String(), nullable=True),
    )
    op.drop_column('group', 'organizationUri')
    op.drop_column('group', 'groupRoleInOrganization')
    op.add_column('share_object', sa.Column('environmentUri', sa.String(), nullable=True))
    op.add_column('tenant_administrator', sa.Column('tenantUri', sa.String(), nullable=False))
    op.create_foreign_key(None, 'tenant_administrator', 'tenant', ['tenantUri'], ['tenantUri'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenant_administrator', type_='foreignkey')
    op.drop_column('tenant_administrator', 'tenantUri')
    op.drop_column('share_object', 'environmentUri')
    op.add_column(
        'group',
        sa.Column('groupRoleInOrganization', sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        'group',
        sa.Column('organizationUri', sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column('environment_group_permission', 'description')
    op.drop_column('environment_group_permission', 'invitedBy')
    op.drop_column('environment_group_permission', 'environmentIAMRoleArn')
    op.drop_column('environment_group_permission', 'environmentIAMRoleName')
    op.drop_column('dataset', 'stewards')
    op.drop_column('dashboardshare', 'owner')
    op.drop_table('tenant_policy_permission')
    op.drop_index(op.f('ix_tenant_policy_principalId'), table_name='tenant_policy')
    op.drop_table('tenant_policy')
    op.drop_table('resource_policy_permission')
    op.drop_index(op.f('ix_tenant_name'), table_name='tenant')
    op.drop_table('tenant')
    op.drop_index(op.f('ix_resource_policy_resourceUri'), table_name='resource_policy')
    op.drop_index(op.f('ix_resource_policy_resourceType'), table_name='resource_policy')
    op.drop_index(op.f('ix_resource_policy_principalId'), table_name='resource_policy')
    op.drop_table('resource_policy')
    op.drop_index(op.f('ix_permission_name'), table_name='permission')
    op.drop_table('permission')
    # ### end Alembic commands ###
