"""mf_foreign_keys_naming_delete_cascade

Revision ID: eddd1f2dc252
Revises: f87aecc36d39
Create Date: 2024-08-19 15:43:25.653159

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eddd1f2dc252'
down_revision = 'f87aecc36d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_attached_mf_uri', 'attached_metadata_form', type_='foreignkey')
    op.create_foreign_key(
        'metadata_form_pkey',
        'attached_metadata_form',
        'metadata_form',
        ['metadataFormUri'],
        ['uri'],
        ondelete='CASCADE',
    )
    op.drop_constraint('fk_attached_field_mf_uri', 'attached_metadata_form_field', type_='foreignkey')
    op.drop_constraint('fk_attached_field_uri', 'attached_metadata_form_field', type_='foreignkey')
    op.create_foreign_key(
        'attached_field_metadata_form_pkey',
        'attached_metadata_form_field',
        'attached_metadata_form',
        ['attachedFormUri'],
        ['uri'],
        ondelete='CASCADE',
    )
    op.create_foreign_key(
        'attached_field_metadata_field_pkey',
        'attached_metadata_form_field',
        'metadata_form_field',
        ['fieldUri'],
        ['uri'],
        ondelete='CASCADE',
    )
    op.drop_constraint('fk_b_field', 'boolean_attached_metadata_form_field', type_='foreignkey')
    op.create_foreign_key(
        'boolean_attached_metadata_form_field_pkey',
        'boolean_attached_metadata_form_field',
        'attached_metadata_form_field',
        ['attachedFormUri', 'fieldUri'],
        ['attachedFormUri', 'fieldUri'],
        ondelete='CASCADE',
    )
    op.drop_constraint('fk_gt_field', 'glossary_term_attached_metadata_form_field', type_='foreignkey')
    op.create_foreign_key(
        'glossary_attached_metadata_form_field_pkey',
        'glossary_term_attached_metadata_form_field',
        'attached_metadata_form_field',
        ['attachedFormUri', 'fieldUri'],
        ['attachedFormUri', 'fieldUri'],
        ondelete='CASCADE',
    )
    op.drop_constraint('fk_i_field', 'integer_attached_metadata_form_field', type_='foreignkey')
    op.create_foreign_key(
        'integer_attached_metadata_form_field_pkey',
        'integer_attached_metadata_form_field',
        'attached_metadata_form_field',
        ['attachedFormUri', 'fieldUri'],
        ['attachedFormUri', 'fieldUri'],
        ondelete='CASCADE',
    )
    op.create_foreign_key(
        'enforcement_metadata_form_pkey',
        'metadata_form_enforcement_rule',
        'metadata_form',
        ['metadataFormUri'],
        ['uri'],
        ondelete='CASCADE',
    )
    op.drop_constraint('fk_mf_filed_form_uri', 'metadata_form_field', type_='foreignkey')
    op.create_foreign_key(
        'field_metadata_form_pkey',
        'metadata_form_field',
        'metadata_form',
        ['metadataFormUri'],
        ['uri'],
        ondelete='CASCADE',
    )
    op.drop_constraint('fk_s_field', 'string_attached_metadata_form_field', type_='foreignkey')
    op.create_foreign_key(
        'string_attached_metadata_form_field_pkey',
        'string_attached_metadata_form_field',
        'attached_metadata_form_field',
        ['attachedFormUri', 'fieldUri'],
        ['attachedFormUri', 'fieldUri'],
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'string_attached_metadata_form_field_pkey', 'string_attached_metadata_form_field', type_='foreignkey'
    )
    op.create_foreign_key(
        'fk_s_field',
        'string_attached_metadata_form_field',
        'attached_metadata_form_field',
        ['attachedFormUri', 'fieldUri'],
        ['attachedFormUri', 'fieldUri'],
    )
    op.drop_constraint('field_metadata_form_pkey', 'metadata_form_field', type_='foreignkey')
    op.create_foreign_key('fk_mf_filed_form_uri', 'metadata_form_field', 'metadata_form', ['metadataFormUri'], ['uri'])
    op.drop_constraint('enforcement_metadata_form_pkey', 'metadata_form_enforcement_rule', type_='foreignkey')
    op.drop_constraint(
        'integer_attached_metadata_form_field_pkey', 'integer_attached_metadata_form_field', type_='foreignkey'
    )
    op.create_foreign_key(
        'fk_i_field',
        'integer_attached_metadata_form_field',
        'attached_metadata_form_field',
        ['attachedFormUri', 'fieldUri'],
        ['attachedFormUri', 'fieldUri'],
    )
    op.drop_constraint(
        'glossary_attached_metadata_form_field_pkey', 'glossary_term_attached_metadata_form_field', type_='foreignkey'
    )
    op.create_foreign_key(
        'fk_gt_field',
        'glossary_term_attached_metadata_form_field',
        'attached_metadata_form_field',
        ['attachedFormUri', 'fieldUri'],
        ['attachedFormUri', 'fieldUri'],
    )
    op.drop_constraint(
        'boolean_attached_metadata_form_field_pkey', 'boolean_attached_metadata_form_field', type_='foreignkey'
    )
    op.create_foreign_key(
        'fk_b_field',
        'boolean_attached_metadata_form_field',
        'attached_metadata_form_field',
        ['attachedFormUri', 'fieldUri'],
        ['attachedFormUri', 'fieldUri'],
    )
    op.drop_constraint('attached_field_metadata_field_pkey', 'attached_metadata_form_field', type_='foreignkey')
    op.drop_constraint('attached_field_metadata_form_pkey', 'attached_metadata_form_field', type_='foreignkey')
    op.create_foreign_key(
        'fk_attached_field_uri', 'attached_metadata_form_field', 'metadata_form_field', ['fieldUri'], ['uri']
    )
    op.create_foreign_key(
        'fk_attached_field_mf_uri',
        'attached_metadata_form_field',
        'attached_metadata_form',
        ['attachedFormUri'],
        ['uri'],
    )
    op.drop_constraint('metadata_form_pkey', 'attached_metadata_form', type_='foreignkey')
    op.create_foreign_key('fk_attached_mf_uri', 'attached_metadata_form', 'metadata_form', ['metadataFormUri'], ['uri'])
    # ### end Alembic commands ###
