"""describe_changes_shortly

Revision ID: f87aecc36d39
Revises: 9efe5f7c69a1
Create Date: 2024-08-17 13:31:54.386554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f87aecc36d39'
down_revision = '9efe5f7c69a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attached_metadata_form_field', 'type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('String', 'Integer', 'Boolean', 'GlossaryTerm', name='metadataformfieldtype'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attached_metadata_form_field', 'type',
               existing_type=sa.Enum('String', 'Integer', 'Boolean', 'GlossaryTerm', name='metadataformfieldtype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
