"""make_mf_values_nullable

Revision ID: fc5a49547ae1
Revises: eddd1f2dc252
Create Date: 2024-08-20 12:58:15.099813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc5a49547ae1'
down_revision = 'eddd1f2dc252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boolean_attached_metadata_form_field', 'value',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('glossary_term_attached_metadata_form_field', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('integer_attached_metadata_form_field', 'value',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('string_attached_metadata_form_field', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('string_attached_metadata_form_field', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('integer_attached_metadata_form_field', 'value',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('glossary_term_attached_metadata_form_field', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('boolean_attached_metadata_form_field', 'value',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
