name: ASH

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ash:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: git clone https://github.com/aws-samples/automated-security-helper.git /tmp/ash
      - name: ASH
        run: /tmp/ash/ash --source-dir .
      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ash-report
          path: aggregated_results.txt
