"""
ORGANIZATION PERMISSIONS
"""
CREATE_ORGANIZATION = 'CREATE_ORGANIZATION'
UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION'
DELETE_ORGANIZATION = 'DELETE_ORGANIZATION'
GET_ORGANIZATION = 'GET_ORGANIZATION'
LINK_ENVIRONMENT = 'LINK_ENVIRONMENT'
INVITE_ORGANIZATION_GROUP = 'INVITE_ORGANIZATION_GROUP'
REMOVE_ORGANIZATION_GROUP = 'REMOVE_ORGANIZATION_GROUP'
ORGANIZATION_ALL = [
    CREATE_ORGANIZATION,
    UPDATE_ORGANIZATION,
    DELETE_ORGANIZATION,
    LINK_ENVIRONMENT,
    GET_ORGANIZATION,
    INVITE_ORGANIZATION_GROUP,
    REMOVE_ORGANIZATION_GROUP,
]
ORGANIZATION_INVITED = [LINK_ENVIRONMENT, GET_ORGANIZATION]

"""
TENANT PERMISSIONS
"""
MANAGE_GROUPS = 'MANAGE_GROUPS'
MANAGE_ENVIRONMENT = 'MANAGE_ENVIRONMENT'
MANAGE_GLOSSARIES = 'MANAGE_GLOSSARIES'
MANAGE_ENVIRONMENTS = 'MANAGE_ENVIRONMENTS'
MANAGE_ORGANIZATIONS = 'MANAGE_ORGANIZATIONS'

"""
ENVIRONMENT
"""
UPDATE_ENVIRONMENT = 'UPDATE_ENVIRONMENT'
GET_ENVIRONMENT = 'GET_ENVIRONMENT'
DELETE_ENVIRONMENT = 'DELETE_ENVIRONMENT'
INVITE_ENVIRONMENT_GROUP = 'INVITE_ENVIRONMENT_GROUP'
REMOVE_ENVIRONMENT_GROUP = 'REMOVE_ENVIRONMENT_GROUP'
UPDATE_ENVIRONMENT_GROUP = 'UPDATE_ENVIRONMENT_GROUP'
ADD_ENVIRONMENT_CONSUMPTION_ROLES = 'ADD_ENVIRONMENT_CONSUMPTION_ROLES'
LIST_ENVIRONMENT_CONSUMPTION_ROLES = 'LIST_ENVIRONMENT_CONSUMPTION_ROLES'
LIST_ENVIRONMENT_GROUP_PERMISSIONS = 'LIST_ENVIRONMENT_GROUP_PERMISSIONS'
LIST_ENVIRONMENT_GROUPS = 'LIST_ENVIRONMENT_GROUPS'
CREDENTIALS_ENVIRONMENT = 'CREDENTIALS_ENVIRONMENT'
ENABLE_ENVIRONMENT_SUBSCRIPTIONS = 'ENABLE_ENVIRONMENT_SUBSCRIPTIONS'
DISABLE_ENVIRONMENT_SUBSCRIPTIONS = 'DISABLE_ENVIRONMENT_SUBSCRIPTIONS'
CREATE_NETWORK = 'CREATE_NETWORK'
LIST_ENVIRONMENT_NETWORKS = 'LIST_ENVIRONMENT_NETWORKS'


ENVIRONMENT_INVITATION_REQUEST = [
    INVITE_ENVIRONMENT_GROUP,
    ADD_ENVIRONMENT_CONSUMPTION_ROLES,
    CREATE_NETWORK,
]

ENVIRONMENT_INVITED_DEFAULT = [
    GET_ENVIRONMENT,
    LIST_ENVIRONMENT_GROUPS,
    LIST_ENVIRONMENT_CONSUMPTION_ROLES,
    LIST_ENVIRONMENT_GROUP_PERMISSIONS,
    LIST_ENVIRONMENT_NETWORKS,
    CREDENTIALS_ENVIRONMENT
]

ENVIRONMENT_INVITED = (ENVIRONMENT_INVITED_DEFAULT + ENVIRONMENT_INVITATION_REQUEST)

ENVIRONMENT_ALL = [
    UPDATE_ENVIRONMENT,
    GET_ENVIRONMENT,
    DELETE_ENVIRONMENT,
    INVITE_ENVIRONMENT_GROUP,
    REMOVE_ENVIRONMENT_GROUP,
    UPDATE_ENVIRONMENT_GROUP,
    LIST_ENVIRONMENT_GROUP_PERMISSIONS,
    ADD_ENVIRONMENT_CONSUMPTION_ROLES,
    LIST_ENVIRONMENT_CONSUMPTION_ROLES,
    LIST_ENVIRONMENT_GROUPS,
    CREDENTIALS_ENVIRONMENT,
    ENABLE_ENVIRONMENT_SUBSCRIPTIONS,
    DISABLE_ENVIRONMENT_SUBSCRIPTIONS,
    CREATE_NETWORK,
    LIST_ENVIRONMENT_NETWORKS,
]
"""
CONSUMPTION_ROLE
"""
REMOVE_ENVIRONMENT_CONSUMPTION_ROLE = 'REMOVE_ENVIRONMENT_CONSUMPTION_ROLE'
CONSUMPTION_ENVIRONMENT_ROLE_ALL = [
    LIST_ENVIRONMENT_CONSUMPTION_ROLES,
    ADD_ENVIRONMENT_CONSUMPTION_ROLES
]
CONSUMPTION_ROLE_ALL = [
    REMOVE_ENVIRONMENT_CONSUMPTION_ROLE
]

"""
GLOSSARIES
"""
CREATE_CATEGORY = 'CREATE_CATEGORY'
CREATE_TERM = 'CREATE_TERM'
UPDATE_NODE = 'UPDATE_NODE'
DELETE_GLOSSARY = 'DELETE_GLOSSARY'
APPROVE_ASSOCIATION = 'APPROVE_ASSOCIATION'
GLOSSARY_ALL = [
    CREATE_CATEGORY,
    CREATE_TERM,
    UPDATE_NODE,
    DELETE_GLOSSARY,
    APPROVE_ASSOCIATION,
]
"""
TENANT ALL
"""

TENANT_ALL = [
    MANAGE_GLOSSARIES,
    MANAGE_GROUPS,
    MANAGE_ENVIRONMENTS,
    MANAGE_ORGANIZATIONS,
]

TENANT_ALL_WITH_DESC = {k: k for k in TENANT_ALL}
TENANT_ALL_WITH_DESC[MANAGE_GLOSSARIES] = 'Manage glossaries'
TENANT_ALL_WITH_DESC[MANAGE_ENVIRONMENTS] = 'Manage environments'
TENANT_ALL_WITH_DESC[MANAGE_GROUPS] = 'Manage teams'
TENANT_ALL_WITH_DESC[MANAGE_ORGANIZATIONS] = 'Manage organizations'

"""
NETWORKS
"""
GET_NETWORK = 'GET_NETWORK'
UPDATE_NETWORK = 'UPDATE_NETWORK'
DELETE_NETWORK = 'DELETE_NETWORK'
NETWORK_ALL = [GET_NETWORK, UPDATE_NETWORK, DELETE_NETWORK]

"""
RESOURCES_ALL
"""
RESOURCES_ALL = (
    ORGANIZATION_ALL
    + ENVIRONMENT_ALL
    + CONSUMPTION_ROLE_ALL
    + GLOSSARY_ALL
    + NETWORK_ALL
)

RESOURCES_ALL_WITH_DESC = {k: k for k in RESOURCES_ALL}
RESOURCES_ALL_WITH_DESC[INVITE_ENVIRONMENT_GROUP] = 'Invite other teams to this environment'
RESOURCES_ALL_WITH_DESC[ADD_ENVIRONMENT_CONSUMPTION_ROLES] = 'Add IAM consumption roles to this environment'
RESOURCES_ALL_WITH_DESC[CREATE_NETWORK] = 'Create networks on this environment'
